version: "3.9"

services:
  main_app:
    image: main_app:v1
    build:
      context: ./main-app
      dockerfile: Dockerfile.dev
    container_name: main_app
    ports:
      - "3000:3000"
    env_file:
      - ./main-app/.env
    volumes:
      - ./main-app:/app
      - main_app_node_modules:/app/node_modules
      - ./main-app/.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command: npm run start:dev
  proctoring_app:
    image: proctoring_app:v1
    build:
      context: ./proctoring-app
      dockerfile: Dockerfile.dev
    container_name: proctoring_app
    ports:
      - "8000:8000"
    volumes:
      - ./proctoring-app:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

volumes:
  main_app_node_modules:
